name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Log into Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the image
      uses: docker/build-push-action@v6.9.0
      with:
        push: true
        tags: axiol/oaos-deploy-history:latest
        secret-envs: SUPABASE_BASE_URL=${{ secrets.SUPABASE_BASE_URL }} | SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
